[package]
name = "llog"
version = "0.1.0"
authors = ["Ng Guoyou <ng.guoyou@gmail.com>"]

[dependencies]
rocket = "0.2.8"
rocket_codegen = "0.2.8"
serde = "1.0.9"
serde_json = "1.0"
serde_derive = "1.0.9"
